import { useLocation, useNavigate, Link } from "react-router-dom";
import { motion } from "framer-motion";
import { jsPDF } from "jspdf";
import { ArrowLeft, Download, RefreshCw, Trophy, XCircle, CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import type { Question } from "@/data/courses";

interface ResultsState {
  questions: Question[];
  answers: (number | null)[];
  courseName: string;
  examType: string;
}

export default function ResultsPage() {
  const location = useLocation();
  const navigate = useNavigate();
  const state = location.state as ResultsState | null;

  if (!state) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Card className="max-w-md">
          <CardContent className="p-6 text-center">
            <XCircle className="h-12 w-12 mx-auto text-destructive mb-4" />
            <h2 className="text-xl font-bold mb-2">No Results Found</h2>
            <p className="text-muted-foreground mb-4">
              Please complete an exam first to see your results.
            </p>
            <Button asChild>
              <Link to="/courses">Take an Exam</Link>
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  const { questions, answers, courseName, examType } = state;

  const correctCount = questions.reduce((count, question, index) => {
    return answers[index] === question.correctAnswer ? count + 1 : count;
  }, 0);

  const percentage = Math.round((correctCount / questions.length) * 100);
  const passed = percentage >= 50;

  const downloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Header
    doc.setFontSize(24);
    doc.setTextColor(0, 150, 200);
    doc.text("ExamPrep Results", pageWidth / 2, 20, { align: "center" });
    
    doc.setFontSize(14);
    doc.setTextColor(100);
    doc.text(`${courseName} - ${examType === "quiz" ? "Quiz" : examType === "mid" ? "Mid Exam" : "Final Exam"}`, pageWidth / 2, 30, { align: "center" });
    
    // Score
    doc.setFontSize(18);
    doc.setTextColor(passed ? 34 : 239, passed ? 197 : 68, passed ? 94 : 68);
    doc.text(`Score: ${correctCount}/${questions.length} (${percentage}%)`, pageWidth / 2, 45, { align: "center" });
    
    doc.setFontSize(12);
    doc.setTextColor(passed ? 34 : 239, passed ? 197 : 68, passed ? 94 : 68);
    doc.text(passed ? "PASSED" : "NEEDS IMPROVEMENT", pageWidth / 2, 52, { align: "center" });
    
    // Line separator
    doc.setDrawColor(200);
    doc.line(20, 58, pageWidth - 20, 58);
    
    // Questions and Answers
    let yPos = 68;
    const lineHeight = 7;
    const maxWidth = pageWidth - 40;
    
    questions.forEach((question, index) => {
      const isCorrect = answers[index] === question.correctAnswer;
      
      // Check if we need a new page
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      
      // Question number and status
      doc.setFontSize(11);
      doc.setTextColor(isCorrect ? 34 : 239, isCorrect ? 197 : 68, isCorrect ? 94 : 68);
      doc.text(`Q${index + 1}: ${isCorrect ? "✓" : "✗"}`, 20, yPos);
      
      // Question text
      doc.setTextColor(50);
      const questionLines = doc.splitTextToSize(question.question, maxWidth - 20);
      doc.text(questionLines, 35, yPos);
      yPos += questionLines.length * lineHeight;
      
      // Your answer
      const yourAnswer = answers[index] !== null ? question.options[answers[index]!] : "Not answered";
      doc.setFontSize(10);
      doc.setTextColor(100);
      const yourAnswerLines = doc.splitTextToSize(`Your answer: ${yourAnswer}`, maxWidth);
      doc.text(yourAnswerLines, 25, yPos);
      yPos += yourAnswerLines.length * lineHeight;
      
      // Correct answer (if wrong)
      if (!isCorrect) {
        doc.setTextColor(34, 197, 94);
        const correctAnswer = question.options[question.correctAnswer];
        const correctLines = doc.splitTextToSize(`Correct: ${correctAnswer}`, maxWidth);
        doc.text(correctLines, 25, yPos);
        yPos += correctLines.length * lineHeight;
      }
      
      yPos += 5;
    });
    
    // Footer
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(`Generated by ExamPrep on ${new Date().toLocaleDateString()}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });
    
    doc.save(`${courseName.replace(/\s+/g, "_")}_${examType}_results.pdf`);
  };

  const handleRetry = () => {
    navigate(`/exam/${location.pathname.split("/")[2]}/${examType}`);
  };

  return (
    <div className="min-h-screen py-12">
      <div className="container mx-auto px-4 max-w-4xl">
        {/* Back Button */}
        <Button variant="ghost" asChild className="mb-6">
          <Link to="/courses">
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to Courses
          </Link>
        </Button>

        {/* Score Card */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <Card className="border-border/50 bg-card/50 backdrop-blur-sm mb-8 overflow-hidden">
            <div className={`h-2 ${passed ? "bg-success" : "bg-destructive"}`} />
            <CardHeader className="text-center pb-2">
              <div className="flex justify-center mb-4">
                {passed ? (
                  <div className="flex h-20 w-20 items-center justify-center rounded-full bg-success/10">
                    <Trophy className="h-10 w-10 text-success" />
                  </div>
                ) : (
                  <div className="flex h-20 w-20 items-center justify-center rounded-full bg-destructive/10">
                    <XCircle className="h-10 w-10 text-destructive" />
                  </div>
                )}
              </div>
              <CardTitle className="text-2xl font-bold">
                {passed ? "Congratulations! 🎉" : "Keep Practicing! 💪"}
              </CardTitle>
              <p className="text-muted-foreground">
                {courseName} - {examType === "quiz" ? "Quiz" : examType === "mid" ? "Mid Exam" : "Final Exam"}
              </p>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="text-center">
                <div className="text-6xl font-bold text-gradient mb-2">{percentage}%</div>
                <p className="text-muted-foreground">
                  {correctCount} out of {questions.length} correct
                </p>
              </div>

              <Progress 
                value={percentage} 
                className={`h-3 ${passed ? "[&>div]:bg-success" : "[&>div]:bg-destructive"}`} 
              />

              <div className="flex flex-col sm:flex-row gap-3">
                <Button onClick={handleRetry} variant="outline" className="flex-1">
                  <RefreshCw className="h-4 w-4 mr-2" />
                  Try Again
                </Button>
                <Button onClick={downloadPDF} className="flex-1 gradient-primary border-0 font-semibold">
                  <Download className="h-4 w-4 mr-2" />
                  Download PDF
                </Button>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Detailed Results */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
        >
          <h2 className="text-2xl font-bold text-foreground mb-6">Detailed Results</h2>
          <div className="space-y-4">
            {questions.map((question, index) => {
              const isCorrect = answers[index] === question.correctAnswer;
              const selectedAnswer = answers[index];

              return (
                <motion.div
                  key={question.id}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.1 * index }}
                >
                  <Card className={`border-l-4 ${isCorrect ? "border-l-success" : "border-l-destructive"} border-border/50 bg-card/50`}>
                    <CardContent className="p-4">
                      <div className="flex items-start gap-3">
                        <div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full ${isCorrect ? "bg-success/10 text-success" : "bg-destructive/10 text-destructive"}`}>
                          {isCorrect ? <CheckCircle2 className="h-5 w-5" /> : <XCircle className="h-5 w-5" />}
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="font-medium text-foreground mb-2">
                            {index + 1}. {question.question}
                          </p>
                          
                          <div className="space-y-1 text-sm">
                            <p className={selectedAnswer !== null ? (isCorrect ? "text-success" : "text-destructive") : "text-muted-foreground"}>
                              <span className="font-medium">Your answer: </span>
                              {selectedAnswer !== null ? question.options[selectedAnswer] : "Not answered"}
                            </p>
                            
                            {!isCorrect && (
                              <p className="text-success">
                                <span className="font-medium">Correct answer: </span>
                                {question.options[question.correctAnswer]}
                              </p>
                            )}
                          </div>

                          <div className={`mt-3 p-3 rounded-lg text-sm ${isCorrect ? "bg-success/5" : "bg-muted/50"}`}>
                            <p className="text-muted-foreground">
                              <span className="font-medium text-foreground">Explanation: </span>
                              {question.explanation}
                            </p>
                          </div>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              );
            })}
          </div>
        </motion.div>

        {/* Bottom Actions */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5 }}
          className="mt-12 text-center"
        >
          <Button asChild size="lg" className="gradient-primary border-0 font-semibold">
            <Link to="/courses">Explore More Courses</Link>
          </Button>
        </motion.div>
      </div>
    </div>
  );
}